class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Navigation
      'nav_dashboard': 'Dashboard',
      'nav_budget': 'Budgets',
      'nav_ledger': 'Ledger',
      'nav_invest': 'Investments',
      'nav_stats': 'Analytics',

      // Dashboard
      'db_total_balance': 'Total Balance',
      'db_net_worth': 'Net Worth',
      'db_portfolio_value': 'Portfolio Value',
      'db_cash_reserves': 'Cash Wallet',
      'db_monthly_income': 'Monthly Income',
      'db_monthly_expense': 'Monthly Expense',
      'db_quick_actions': 'Quick Actions',
      'db_recent_activity': 'Recent Activity',
      'db_no_recent_transactions': 'No recent transactions',
      
      // Daily Tracker (Ledger)
      'tr_ledger_title': 'Financial Ledger',
      'tr_add_transaction': 'Add Transaction',
      'tr_edit_transaction': 'Edit Transaction',
      'tr_title': 'Title',
      'tr_amount': 'Amount',
      'tr_type': 'Type',
      'tr_category': 'Category',
      'tr_date': 'Date',
      'tr_notes': 'Notes (Optional)',
      'tr_income': 'Income',
      'tr_expense': 'Expense',
      'tr_search_placeholder': 'Search transactions...',
      'tr_all': 'All',
      'tr_filter_category': 'Filter by Category',
      'tr_sort_by': 'Sort By',
      'tr_sort_date_new': 'Date (Newest)',
      'tr_sort_date_old': 'Date (Oldest)',
      'tr_sort_amount_high': 'Amount (Highest)',
      'tr_sort_amount_low': 'Amount (Lowest)',
      'tr_transaction_saved': 'Transaction saved successfully',
      'tr_transaction_deleted': 'Transaction deleted',
      'tr_empty_ledger': 'Your ledger is empty. Tap + to record your first transaction!',
      'tr_delete_confirm': 'Delete Transaction?',
      'tr_delete_confirm_body': 'Are you sure you want to delete this transaction?',

      // Budgets
      'bg_budget_title': 'Category Budgets',
      'bg_add_budget': 'Set New Budget',
      'bg_edit_budget': 'Edit Budget',
      'bg_limit': 'Limit Amount',
      'bg_spent': 'Spent',
      'bg_remaining': 'Remaining',
      'bg_over_budget': 'Exceeded by',
      'bg_healthy': 'Healthy (Under Limit)',
      'bg_status_all': 'All Budgets',
      'bg_status_healthy': 'Under Limit',
      'bg_status_exceeded': 'Exceeded',
      'bg_sort_name': 'Category Name',
      'bg_sort_limit': 'Limit (High to Low)',
      'bg_sort_percent': 'Usage % (High to Low)',
      'bg_empty_budget': 'No budgets set. Tap + to set a target!',
      'bg_delete_confirm': 'Delete Budget?',
      'bg_delete_confirm_body': 'Are you sure you want to delete this budget?',

      // Investments
      'iv_invest_title': 'Asset Simulator',
      'iv_portfolio_performance': 'Portfolio Performance',
      'iv_realtime_prices': 'Live Market Prices',
      'iv_market_closed': 'Market Data Offline (Simulated)',
      'iv_price_source': 'Price Source',
      'iv_api_live': 'Live Yahoo API',
      'iv_api_sim': 'Simulated Fallback',
      'iv_refresh_prices': 'Refresh Market Prices',
      'iv_holdings': 'Your Holdings',
      'iv_market': 'Market Assets',
      'iv_buy': 'Buy',
      'iv_sell': 'Sell',
      'iv_quantity': 'Quantity',
      'iv_price': 'Price',
      'iv_avg_price': 'Avg Buy Price',
      'iv_current_value': 'Current Value',
      'iv_total_cost': 'Total Cost',
      'iv_unrealized_profit': 'Unrealized P&L',
      'iv_insufficient_cash': 'Insufficient cash reserves!',
      'iv_insufficient_shares': 'Insufficient assets owned to sell!',
      'iv_trade_success': 'Trade executed successfully!',
      'iv_search_asset': 'Search tickers...',
      'iv_filter_category': 'Filter Category',
      'iv_sort_ticker': 'Ticker (A-Z)',
      'iv_sort_value': 'Holdings Value',
      'iv_sort_profit': 'Profitability %',
      'iv_empty_holdings': 'No active holdings. Trade assets in the Market tab!',
      'iv_buy_shares': 'Buy {ticker}',
      'iv_sell_shares': 'Sell {ticker}',

      // Analytics (Stats)
      'st_stats_title': 'Financial Intelligence',
      'st_expense_allocation': 'Expense Distribution',
      'st_income_vs_expense': 'Cash Flow Trend',
      'st_timeframe_week': 'Last 7 Days',
      'st_timeframe_month': 'Current Month',
      'st_no_data': 'Insufficient transactions in this period to display charts',
      'st_total_spending': 'Total Spending',

      // Evening Reminders
      'rm_banner_title': 'Evening Ledger Review',
      'rm_banner_body': 'You haven\'t logged any transactions today. Record your expenses to maintain healthy financial tracking!',
      'rm_settings_title': 'Reminder Notifications',
      'rm_enable_reminder': 'Enable Daily Reminder',
      'rm_reminder_time': 'Reminder Time',
      'rm_trigger_mock': 'Test Reminder Notification',
      'rm_notification_title': 'Daily Expense Reminder',
      'rm_notification_body': 'Don\'t forget to record today\'s expenses and incomes to keep your budget healthy!',

      // Categories
      'cat_food': 'Food & Drinks',
      'cat_transport': 'Transportation',
      'cat_utilities': 'Bills & Utilities',
      'cat_entertainment': 'Entertainment',
      'cat_shopping': 'Shopping',
      'cat_salary': 'Salary Income',
      'cat_dividends': 'Invest Dividends',
      'cat_other': 'Other Details',
      'cat_stocks': 'Stocks',
      'cat_crypto': 'Cryptocurrencies',
      'cat_metals': 'Precious Metals',

      // UI general
      'ui_settings': 'Settings',
      'ui_language': 'Language / Ngôn ngữ',
      'ui_save': 'Save',
      'ui_cancel': 'Cancel',
      'ui_delete': 'Delete',
      'ui_confirm': 'Confirm',
      'ui_close': 'Close',
      'ui_loading': 'Processing...',
      'ui_error_invalid_amount': 'Please enter a valid positive number',
      'ui_error_invalid_title': 'Please enter a valid title',
    },
    'vi': {
      // Navigation
      'nav_dashboard': 'Tổng quan',
      'nav_budget': 'Ngân sách',
      'nav_ledger': 'Sổ thu chi',
      'nav_invest': 'Đầu tư',
      'nav_stats': 'Phân tích',

      // Dashboard
      'db_total_balance': 'Tổng tài sản',
      'db_net_worth': 'Tài sản ròng',
      'db_portfolio_value': 'Tài sản đầu tư',
      'db_cash_reserves': 'Ví tiền mặt',
      'db_monthly_income': 'Thu nhập tháng',
      'db_monthly_expense': 'Chi tiêu tháng',
      'db_quick_actions': 'Thao tác nhanh',
      'db_recent_activity': 'Giao dịch gần đây',
      'db_no_recent_transactions': 'Chưa có giao dịch nào gần đây',
      
      // Daily Tracker (Ledger)
      'tr_ledger_title': 'Sổ thu chi tài chính',
      'tr_add_transaction': 'Thêm giao dịch',
      'tr_edit_transaction': 'Sửa giao dịch',
      'tr_title': 'Tiêu đề',
      'tr_amount': 'Số tiền',
      'tr_type': 'Loại',
      'tr_category': 'Danh mục',
      'tr_date': 'Ngày giao dịch',
      'tr_notes': 'Ghi chú (Không bắt buộc)',
      'tr_income': 'Khoản thu',
      'tr_expense': 'Khoản chi',
      'tr_search_placeholder': 'Tìm kiếm giao dịch...',
      'tr_all': 'Tất cả',
      'tr_filter_category': 'Lọc theo danh mục',
      'tr_sort_by': 'Sắp xếp theo',
      'tr_sort_date_new': 'Ngày (Mới nhất)',
      'tr_sort_date_old': 'Ngày (Cũ nhất)',
      'tr_sort_amount_high': 'Số tiền (Cao nhất)',
      'tr_sort_amount_low': 'Số tiền (Thấp nhất)',
      'tr_transaction_saved': 'Đã lưu giao dịch thành công',
      'tr_transaction_deleted': 'Đã xóa giao dịch',
      'tr_empty_ledger': 'Sổ thu chi trống. Nhấn + để ghi chép khoản đầu tiên!',
      'tr_delete_confirm': 'Xóa giao dịch?',
      'tr_delete_confirm_body': 'Bạn có chắc chắn muốn xóa giao dịch này không?',

      // Budgets
      'bg_budget_title': 'Ngân sách chi tiêu',
      'bg_add_budget': 'Thiết lập ngân sách',
      'bg_edit_budget': 'Sửa ngân sách',
      'bg_limit': 'Hạn mức chi tiêu',
      'bg_spent': 'Đã chi',
      'bg_remaining': 'Còn lại',
      'bg_over_budget': 'Vượt hạn mức',
      'bg_healthy': 'Hợp lý (Dưới hạn mức)',
      'bg_status_all': 'Tất cả ngân sách',
      'bg_status_healthy': 'Dưới hạn mức',
      'bg_status_exceeded': 'Vượt hạn mức',
      'bg_sort_name': 'Tên danh mục',
      'bg_sort_limit': 'Hạn mức (Cao đến Thấp)',
      'bg_sort_percent': 'Tỷ lệ sử dụng (Cao đến Thấp)',
      'bg_empty_budget': 'Chưa thiết lập ngân sách. Nhấn + để đặt mục tiêu!',
      'bg_delete_confirm': 'Xóa ngân sách?',
      'bg_delete_confirm_body': 'Bạn có chắc chắn muốn xóa ngân sách này không?',

      // Investments
      'iv_invest_title': 'Trình mô phỏng đầu tư',
      'iv_portfolio_performance': 'Hiệu suất danh mục',
      'iv_realtime_prices': 'Giá thị trường trực tuyến',
      'iv_market_closed': 'Thị trường ngoại tuyến (Mô phỏng)',
      'iv_price_source': 'Nguồn giá',
      'iv_api_live': 'Yahoo API trực tiếp',
      'iv_api_sim': 'Mô phỏng dự phòng',
      'iv_refresh_prices': 'Cập nhật giá thị trường',
      'iv_holdings': 'Tài sản sở hữu',
      'iv_market': 'Tài sản thị trường',
      'iv_buy': 'Mua',
      'iv_sell': 'Bán',
      'iv_quantity': 'Số lượng',
      'iv_price': 'Giá trị',
      'iv_avg_price': 'Giá mua trung bình',
      'iv_current_value': 'Giá trị hiện tại',
      'iv_total_cost': 'Tổng vốn đầu tư',
      'iv_unrealized_profit': 'Lợi nhuận tạm tính',
      'iv_insufficient_cash': 'Ví tiền mặt không đủ số dư!',
      'iv_insufficient_shares': 'Không đủ số lượng tài sản để bán!',
      'iv_trade_success': 'Giao dịch thành công!',
      'iv_search_asset': 'Tìm mã tài sản...',
      'iv_filter_category': 'Phân loại danh mục',
      'iv_sort_ticker': 'Mã tài sản (A-Z)',
      'iv_sort_value': 'Giá trị sở hữu',
      'iv_sort_profit': 'Mức sinh lời %',
      'iv_empty_holdings': 'Chưa sở hữu tài sản nào. Giao dịch ngay tại tab Thị trường!',
      'iv_buy_shares': 'Mua {ticker}',
      'iv_sell_shares': 'Bán {ticker}',

      // Analytics (Stats)
      'st_stats_title': 'Phân tích tài chính',
      'st_expense_allocation': 'Cơ cấu chi tiêu',
      'st_income_vs_expense': 'Xu hướng dòng tiền',
      'st_timeframe_week': '7 ngày qua',
      'st_timeframe_month': 'Tháng hiện tại',
      'st_no_data': 'Không đủ dữ liệu giao dịch trong kỳ để hiển thị biểu đồ',
      'st_total_spending': 'Tổng chi tiêu',

      // Evening Reminders
      'rm_banner_title': 'Nhắc nhở ghi chép tối',
      'rm_banner_body': 'Bạn chưa ghi nhận giao dịch nào hôm nay. Hãy cập nhật sổ thu chi để kiểm soát tài chính tốt hơn!',
      'rm_settings_title': 'Nhắc nhở hàng ngày',
      'rm_enable_reminder': 'Kích hoạt nhắc nhở',
      'rm_reminder_time': 'Thời gian nhắc nhở',
      'rm_trigger_mock': 'Thử nghiệm thông báo',
      'rm_notification_title': 'Nhắc nhở cập nhật chi tiêu',
      'rm_notification_body': 'Đừng quên ghi chép lại các khoản thu chi hôm nay để giữ ngân sách của bạn luôn hợp lý nhé!',

      // Categories
      'cat_food': 'Ăn uống / Nhà hàng',
      'cat_transport': 'Di chuyển / Đi lại',
      'cat_utilities': 'Hóa đơn & Dịch vụ',
      'cat_entertainment': 'Vui chơi & Giải trí',
      'cat_shopping': 'Mua sắm cá nhân',
      'cat_salary': 'Lương thu nhập',
      'cat_dividends': 'Lợi tức đầu tư',
      'cat_other': 'Khoản chi tiêu khác',
      'cat_stocks': 'Cổ phiếu',
      'cat_crypto': 'Tiền kỹ thuật số',
      'cat_metals': 'Kim loại quý / Vàng',

      // UI general
      'ui_settings': 'Cài đặt',
      'ui_language': 'Ngôn ngữ / Language',
      'ui_save': 'Lưu lại',
      'ui_cancel': 'Hủy bỏ',
      'ui_delete': 'Xóa bỏ',
      'ui_confirm': 'Xác nhận',
      'ui_close': 'Đóng',
      'ui_loading': 'Đang xử lý...',
      'ui_error_invalid_amount': 'Vui lòng nhập số hợp lệ lớn hơn 0',
      'ui_error_invalid_title': 'Vui lòng nhập tiêu đề hợp lệ',
    }
  };

  static String translate(String key, String lang, {Map<String, String>? params}) {
    final language = _localizedValues.containsKey(lang) ? lang : 'en';
    var text = _localizedValues[language]?[key] ?? key;
    
    if (params != null) {
      params.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    
    return text;
  }
}
